"""Generate the local environment files needed to run the stack.

Writes two gitignored files from one source of truth, so credentials cannot
drift between the services and the infrastructure they talk to:

``.env``
    Everything the four application services need, including the signing and
    key-wrapping PEMs.

``.env.infra``
    Only what the Postgres and RabbitMQ images need to initialize themselves.
    Deliberately minimal: the infrastructure containers have no business
    holding the private keys, and anything in their environment is visible to
    ``docker inspect``.

Usage:
    python scripts/bootstrap_env.py            # refuse to clobber existing files
    python scripts/bootstrap_env.py --force    # regenerate, new keys and passwords

Keys are generated once here and then persist in ``.env`` across restarts,
which is what RULES.md requires. Running with ``--force`` generates new keys
and invalidates any packet signed with the old ones.
"""

from __future__ import annotations

import argparse
import secrets
import sys
from pathlib import Path

from shared.crypto import generate_rsa_keypair, generate_signing_keypair

REPO_ROOT = Path(__file__).resolve().parent.parent
ENV_PATH = REPO_ROOT / ".env"
ENV_INFRA_PATH = REPO_ROOT / ".env.infra"


def _escape_pem(pem: str) -> str:
    """Flatten a PEM into a single env-safe line."""
    return pem.strip().replace("\n", "\\n")


def _password() -> str:
    """A URL-safe password.

    Restricted to the base64url alphabet on purpose: characters like ``$``
    would be interpreted by Docker Compose interpolation, and quotes would
    break naive env-file parsers.
    """
    return secrets.token_urlsafe(24)


def build_files() -> tuple[str, str]:
    """Render the contents of `.env` and `.env.infra` with matching credentials."""
    postgres_password = _password()
    rabbitmq_password = _password()
    postgres_user = "meshsettle"
    postgres_db = "meshsettle"
    rabbitmq_user = "meshsettle"

    signing_private, signing_public = generate_signing_keypair()
    rsa_private, rsa_public = generate_rsa_keypair()

    env = f"""# MeshSettle local environment. Generated by scripts/bootstrap_env.py.
# Gitignored. Contains real private keys. Never commit, never share.

# --- Postgres ---
POSTGRES_USER={postgres_user}
POSTGRES_PASSWORD={postgres_password}
POSTGRES_DB={postgres_db}
# Host/port for running services directly on your machine. docker-compose.yml
# overrides these with the compose service names.
POSTGRES_HOST=localhost
POSTGRES_PORT=5432

# --- Redis (dedupe store) ---
REDIS_URL=redis://localhost:6379/0
DEDUPE_TTL_SECONDS=86400
DEDUPE_CLAIM_TTL_SECONDS=60

# --- RabbitMQ ---
RABBITMQ_USER={rabbitmq_user}
RABBITMQ_PASSWORD={rabbitmq_password}
RABBITMQ_HOST=localhost
RABBITMQ_PORT=5672
SETTLEMENT_QUEUE=meshsettle.settlements

# --- Crypto keys (generated once; regenerating invalidates old signatures) ---
SENDER_SIGNING_PRIVATE_KEY_PEM="{_escape_pem(signing_private)}"
SENDER_SIGNING_PUBLIC_KEY_PEM="{_escape_pem(signing_public)}"
SETTLEMENT_RSA_PRIVATE_KEY_PEM="{_escape_pem(rsa_private)}"
SETTLEMENT_RSA_PUBLIC_KEY_PEM="{_escape_pem(rsa_public)}"

# --- Mesh simulation ---
MESH_HOP_COUNT=2
MESH_HOP_LIMIT=16
MESH_NODE_ID=relay-1
MESH_RELAY_URL=http://localhost:8002
BRIDGE_URL=http://localhost:8003
MESH_FORWARD_TIMEOUT_SECONDS=5.0

# --- Rate limiting ---
RATE_LIMIT_PER_MINUTE=60

# --- Logging ---
LOG_LEVEL=INFO
"""

    env_infra = f"""# MeshSettle infrastructure credentials. Generated by scripts/bootstrap_env.py.
# Gitignored. Only what the Postgres and RabbitMQ images need to initialize;
# no private keys belong in here.
#
# These MUST match the corresponding values in .env. Both files are written
# together so they cannot drift.

POSTGRES_USER={postgres_user}
POSTGRES_PASSWORD={postgres_password}
POSTGRES_DB={postgres_db}

RABBITMQ_DEFAULT_USER={rabbitmq_user}
RABBITMQ_DEFAULT_PASS={rabbitmq_password}
"""
    return env, env_infra


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python scripts/bootstrap_env.py",
        description="Generate .env and .env.infra for local development.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="overwrite existing files, generating new keys and passwords",
    )
    args = parser.parse_args(argv)

    existing = [path for path in (ENV_PATH, ENV_INFRA_PATH) if path.exists()]
    if existing and not args.force:
        names = ", ".join(path.name for path in existing)
        print(f"refusing to overwrite existing {names}; pass --force to regenerate")
        return 1

    env, env_infra = build_files()
    ENV_PATH.write_text(env)
    ENV_INFRA_PATH.write_text(env_infra)
    # Owner-only: these hold private keys and database credentials.
    ENV_PATH.chmod(0o600)
    ENV_INFRA_PATH.chmod(0o600)

    print(f"wrote {ENV_PATH.name} and {ENV_INFRA_PATH.name} (mode 600)")
    print("credentials match across both files; keys will persist across restarts")
    return 0


if __name__ == "__main__":
    sys.exit(main())
